name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        max-parallel: 3
        fail-fast: false
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
          include:
            - images: amd64/alpine
              os: ubuntu-22.04
          exclude:
            - images: alpine
              os: windows-latest
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info
   
      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}