name: Variables and Secrets

on:  
#  schedule:
#    - cron: '*/1 * * * *'
   push:
   workflow_dispatch:

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: siddharth1
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: |
        echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 1
    concurrency: 
      group: production-deployment
      cancel-in-progress: true
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: |
        echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        sleep 600s